Bugfix/correct intents
student-hub/chatbot pull request #27
Opened 2021-08-20 15:17 UTC by andreeatogoe

2021-08-20 16:03 UTC, ancadavid requested changes

2021-08-20 16:03 UTC, ancadavid commented on intents/faq/ro/ask_SRLeaderTasks.yml
> +    - Vreau sa stiu ce trebuie sa faca un sef de serie!
diacritice: să, facă

2021-08-20 16:03 UTC, ancadavid commented on intents/faq/ro/ask_connectEduroamWiFi.yml
> +    - Zi-mi cum fac sa ma conectez la retelele Wi-fi Eduroam?
diacritice

2021-08-20 16:03 UTC, ancadavid commented on intents/faq/ro/ask_connectOutlook.yml
> +    - Știi cum sa mă conectez pe Outlook?
diacritice

2021-08-22 12:59 UTC, gabrielGavriluta approved these changes

2021-08-23 20:49 UTC, ancadavid approved these changes

2021-08-24 05:40 UTC, merged